### PR TITLE
Fix issue when bootstrapping on 2.x

### PR DESCRIPTION
**Pull request by huyaboo**
### Description

Fixes bootstrap within `2.x` branch caused by #7194 . This is due to `@opensearch-project/opensearch` major version difference between `main` and `2.x`, which has interface changes that break bootstrap (#3464).

## Changelog
- fix: Fix bootstrap errors in 2.x

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by zhyuanqi — APPROVED** [review]

**Review by BionIT — APPROVED** [review]

**Comment by Hailong-am** [comment]
will this fixed OSD start issue, try to build a distribution and start OSD, it reports error as below

```
➜  opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64 ./bin/opensearch-dashboards
Error: Cannot find module './mocks'
Require stack:
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/config/index.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/discovery/plugin_manifest_parser.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/discovery/index.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/plugins_service.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/index.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/index.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/cli/serve/serve.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/cli/cli.js
- /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/cli/dist.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Module.Hook._require.Module.require (/local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/config/index.js:156:14)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at Module.Hook._require.Module.require (/local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/node_modules/require-in-the-middle/index.js:80:39)
➜  opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64

```

**Comment by huyaboo** [comment]
> @huyaboo will this fixed OSD start issue? Try to build a distribution and start OSD, it reports error as below
> 
> https://github.com/opensearch-project/OpenSearch-Dashboards/blob/a857941a44bf190b199b222a135274ed98d803ae/src/core/server/config/index.ts#L33
> 
> ```
> ➜  opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64 ./bin/opensearch-dashboards
> Error: Cannot find module './mocks'
> Require stack:
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/config/index.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/discovery/plugin_manifest_parser.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/discovery/index.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/plugins_service.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/plugins/index.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/index.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/cli/serve/serve.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/cli/cli.js
> - /local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/cli/dist.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
>     at Module.Hook._require.Module.require (/local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/node_modules/require-in-the-middle/index.js:61:29)
>     at require (internal/modules/cjs/helpers.js:107:18)
>     at Object.<anonymous> (/local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/src/core/server/config/index.js:156:14)
>     at Module._compile (internal/modules/cjs/loader.js:1114:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
>     at Module.load (internal/modules/cjs/loader.js:979:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
>     at Module.require (internal/modules/cjs/loader.js:1003:19)
>     at Module.Hook._require.Module.require (/local/home/ihailong/build/opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64/node_modules/require-in-the-middle/index.js:80:39)
> ➜  opensearch-dashboards-3.0.0-SNAPSHOT-linux-x64
> ```

No, but #7922 does
