### PR TITLE
Fix issue connecting to data source with SigV4 auth after upgrading aws sdk from v2 to v3

### PR DESCRIPTION
**Pull request by cwperks**
### Description

This PR fixes an error when configuring a data source with SigV4 auth that was a regression from upgrading the aws sdk from v2 to v3 in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9641. While https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9641 fixed an issue when configuring a data source with basic auth credentials after upgrading OSD Core from node18 -> node20, it broke sigv4 auth.

This PR contains the following changes.

1. Use AbortController from aws-sdk v3 to abort request
2. Remove `import { Credentials } from '@aws-sdk/client-sts';` and pass creds directly

This error was discovered on future playground with the following message:

`TypeError: request.abort is not a function`

### Testing

I verified that SigV4 auth works by connecting to an AOS domain from my localhost when configuring a datasource.

## Changelog
- fix: Fix issue connecting to data source with SigV4 auth after upgrading aws sdk from v2 to v3

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by cwperks** [comment]
Taking out of draft as I was able to verify connection to an AOS domain using SigV4 auth when configuring a data source

File: src/plugins/data_source/server/legacy/http_aws_es/connector.test.js [hunk 1]
```diff
@@ -48,33 +48,6 @@ describe('request', function () {
...
-    const cancel = connector.request({}, () => {});
-
-    // since getCredentials is async, we have to let the event loop tick
-    setTimeout(() => {
-      try {
-        expect(cancel).to.be.a('function');
-
-        cancel();
-
-        expect(fakeReq.abort.called).to.be.true;
```
[the remark this answers is not in the document]
Comment (cwperks) [reply src/plugins/data_source/server/legacy/http_aws_es/connector.test.js:69]: To run this single test suite use `scripts/use_node scripts/jest --ci --colors --runInBand --coverage --ci-group=3 --testPathPattern=src/plugins/data_source/server/legacy/http_aws_es/connector.test.js`

**Review by zhongnansu — APPROVED** [review]

File: src/plugins/data_source/server/legacy/http_aws_es/connector.js [hunk 2]
```diff
@@ -115,7 +110,7 @@ class HttpAmazonESConnector extends HttpConnector {
     return request;
   }
 
-  signRequest(request, credentials) {
+  async signRequest(request, credentials) {
```
Comment (kavilla) [inline src/plugins/data_source/server/legacy/http_aws_es/connector.js:113]: How come? Is signing it async?

**Review by kavilla — APPROVED** [review]
